version: "3"

services:
  todo-mongo:
    image: mongo
    ports:
      - "27017:27017"

  todo-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - todo-mongo

  todo-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
